//tealium universal tag - utag.25 ut4.0.201610050933, Copyright 2016 Tealium.com Inc. All Rights Reserved.
var criteo_q=criteo_q||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState==='complete'||this.readyState==='loaded')&&!b.hFlag){b.hFlag=1;o.cb();}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb();}};}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.known_params={"product":1,"order_id":1,"transaction_id":1,"product.id":1,"product.price":1,"product.quantity":1,"event":1,"requiresDOM":1,"account":1,"keywords":1,"new_customer":1,"deduplication":1,"site_type":1,"email":1,"login":1,"hashed_email":1,"hashed_login":1};u.isEmpty=function(value){if((value==="")||(value.constructor===Array&&value.length===0)){return true;}else{return false;}};u.prep=function(value,alwaysConvert){if(typeof value==="string"&&(alwaysConvert||value.indexOf(",")>0)){value=value.split(",");}
return value;};u.map={"criteo_partner_id":"account","criteo_site_type":"site_type","criteo_event":"event","search_term":"keywords","criteo_product_id":"product.id","criteo_product_price":"product.price","criteo_product_quantity":"product.quantity","logged_in_customer_id":"customer_id","cp.criteo_dedupe":"deduplication","criteo_section":"section","criteo_segment":"user_segment","cp.__adi_rt_DkpyPh8":"test_group","cp.customer_hashed_email_pers":"hashed_email","analytics_pagename":"section"};u.extend=[function(a,b){if(document.location.hostname.indexOf('miteam')>-1){return false;}},function(a,b,c,d,e,f,g){d=b['country'];if(typeof d=='undefined')return;c=[{'AR':'12257'},{'AT':'8405'},{'AU':'8683'},{'BE':'8410'},{'BR':'7688'},{'CA':'19035'},{'CL':'11237'},{'CO':'11236'},{'CZ':'15486'},{'DE':'978'},{'DK':'8407'},{'ES':'7373'},{'FI':'8409'},{'FR':'977'},{'GR':'20034'},{'IE':'8406'},{'IT':'7374'},{'MX':'12259'},{'NL':'6019'},{'NZ':'11975'},{'PE':'19377'},{'PL':'11891'},{'PT':'20035'},{'RU':'9925'},{'SE':'8408'},{'SK':'15487'},{'UK':'976'},{'US':'4805'},{'NO':'33025'},{'CH':'33026'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['criteo_partner_id']=c[e][f];m=true};};if(m)break};if(!m)b['criteo_partner_id']='';},function(a,b,c,d,e,f,g){d=b['page_type'];if(typeof d=='undefined')return;c=[{'(CLP|SEARCH|PLP)':'viewList'},{'CART':'viewBasket'},{'CHECKOUT':'trackTransaction'},{'(HOME|BRAND)':'viewHome'},{'PDP':'viewItem'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){g=new RegExp(f,'i');if(g.test(d)){b['criteo_event']=c[e][f];m=true};};if(m)break};if(!m)b['criteo_event']='';},function(a,b){if(b.page_type=='CLP'){if(b.filter_sport=='FOOTBALL'){b.criteo_section='football';}else if(b.filter_sport=='BASKETBALL'){b.criteo_section='basketball';}else if(b.filter_brand=='ORIGINALS'){b.criteo_section='originals';}else if(b.filter_sport=='RUNNING'){b.criteo_section='running';}else if(b.filter_brand=='ADIDAS BY STELLA MCCARTNEY'){b.criteo_section='stella_mccartney';}else if(b.filter_sport=='GOLF'){b.criteo_section='golf';}else if(b.filter_sport=='MICOACH'){b.criteo_section='micoach';}else if(b.filter_sport=='TRAINING'){b.criteo_section='training';}else if(b.filter_sport=='TENNIS'){b.criteo_section='tennis';}else if(b.filter_brand=='ADIDAS NEO'){b.criteo_section='adidasneo';}else if(b.filter_brand=='PORSCHE DESIGN SPORT'){b.criteo_section='porsche_design_sport';}}},function(a,b){try{if(1){b['criteo_site_type']='d'}}catch(e){utag.DB(e)}},function(a,b){try{if(b['is_mobile'].toString().toLowerCase()=='TRUE'.toLowerCase()){b['criteo_site_type']='m'}}catch(e){utag.DB(e)}},function(a,b){try{if(b['qp.cm_mmc'].toString().toLowerCase().indexOf('AdieEmail_MKTG-_-Newsletter-_-Event_Xmas'.toLowerCase())>-1){b['criteo_segment']='99'}}catch(e){utag.DB(e)}},function(a,b){if(b.criteo_event=='trackTransaction'&&!b.order_id){b.criteo_event='';}
if(!b.criteo_event||(b.event||b.event_name||b.event_category||b.current_filter)){return false;}
if(!b.criteo_product_id){if(b.product_model_id){b.criteo_product_id=b.product_model_id.slice(0,!(b.page_type=='CHECKOUT'||b.page_type=='SHOPPING CART')?3:b.product_model_id.length);}else if(b.product_id){b.criteo_product_id=b.product_id.slice(0,3);}}
if(typeof(b.criteo_product_id)=='object'){b.criteo_product_price=[];b.criteo_product_quantity=[];for(var i=0;i<b.criteo_product_id.length;i++){if(b.product_quantity&&b.product_quantity[i]){b.criteo_product_quantity.push(b.product_quantity[i]);}
var price;if(b.product_price&&b.product_price[i]){price=b.product_price[i];}else if(b.product_price_vat&&b.product_price_vat[i]){price=b.product_price_vat[i];}else{price='1';}
if(b.country=='PL'||b.country=='CZ'){price=tealiumiq_currency.convert(price,b.currency_code,'EUR');}
b.criteo_product_price.push(price);}
if(b.order_id&&b.country!="US"){b.criteo_product_id.push('shipping');b.criteo_product_price.push(!(b.country=='PL'||b.country=='CZ')?b.shipping_total:tealiumiq_currency.convert(b.shipping_total,b.currency_code,'EUR'));b.criteo_product_quantity.push('1');}}},function(a,b){b['cp.__adi_rt_DkpyPh8']=b['cp.__adi_rt_DkpyPh8']||utag.loader.RC('__adi_rt_DkpyPh8');if(typeof(b['cp.__adi_rt_DkpyPh8'])=='object'){b['cp.__adi_rt_DkpyPh8']='';}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"base_url":""||"//static.criteo.net/js/ld/ld.js","account":"978","event":"viewHome","deduplication":1,"new_customer":"","keywords":"","setData":{},"site_type":"d","email":[],"login":[],"hashed_email":[],"hashed_login":[],"order_id":"","product_id":[],"product_quantity":[],"product_unit_price":[]};var t_criteo_q=[];for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(!u.known_params[e[f]]){u.data.setData[e[f]]=b[d];}else{u.data[e[f]]=b[d];}}}}
u.data.order_id=u.data.order_id||b._corder||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.data.transaction_id=u.data.transaction_id||u.data.order_id;u.data.product_id=u.data["product.id"]||u.data.product_id;u.data.product_unit_price=u.data["product.price"]||u.data.product_unit_price;u.data.product_quantity=u.data["product.quantity"]||u.data.product_quantity;if(!u.isEmpty(u.data.account)){t_criteo_q.push({"event":"setAccount","account":u.prep(u.data.account,false)});}else{utag.DB("error:25:Criteo Account ID Missing");return;}
if(!u.isEmpty(u.data.site_type)){t_criteo_q.push({"event":"setSiteType","type":u.data.site_type});}
if(!u.isEmpty(u.data.email)){t_criteo_q.push({"event":"setEmail","email":u.prep(u.data.email,true)});}
if(!u.isEmpty(u.data.login)){t_criteo_q.push({"event":"setLogin","login":u.prep(u.data.login,true)});}
if(!u.isEmpty(u.data.hashed_email)){t_criteo_q.push({"event":"setHashedEmail","email":u.prep(u.data.hashed_email,true)});}
if(!u.isEmpty(u.data.hashed_login)){t_criteo_q.push({"event":"setHashedLogin","login":u.prep(u.data.hashed_login,true)});}
for(d in u.data.setData){var c={"event":"setData"};c[d]=u.data.setData[d];t_criteo_q.push(c);}
if(u.data.transaction_id){f={event:"trackTransaction",id:u.data.transaction_id,new_customer:u.data.new_customer,deduplication:u.data.deduplication,product:[]};for(d=0;d<u.data.product_id.length;d++){f.product.push({id:u.data.product_id[d],price:u.data.product_unit_price[d],quantity:u.data.product_quantity[d]});}
t_criteo_q.push(f);}
if(u.data.event.indexOf("viewHome")>-1){t_criteo_q.push({event:"viewHome"});}
if(u.data.event.indexOf("viewItem")>-1){u.data.product_id=u.data["product.id"]||u.data.product_id[0];t_criteo_q.push({event:"viewItem",product:u.data.product_id});}
if(u.data.event.indexOf("viewList")>-1){t_criteo_q.push({event:"viewList",product:u.data.product_id,keywords:u.data.keywords});}
if(u.data.event.indexOf("viewBasket")>-1){f={event:"viewBasket",product:[]};for(d=0;d<u.data.product_id.length;d++){f.product.push({id:u.data.product_id[d],price:u.data.product_unit_price[d],quantity:u.data.product_quantity[d]});}
t_criteo_q.push(f);}
if(u.data.event.indexOf("viewSearch")>-1){t_criteo_q.push({event:"viewSearch"});}
criteo_q.push(t_criteo_q);u.loader_cb=function(){u.initialized=true;};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_25'});}
}};utag.o[loader].loader.LOAD(id);}('25','adidas.adidasglobal'));}catch(error){utag.DB(error);}
